name: hybrid_translator
description: "Advanced Hybrid Translator — Voice & Text, Online & Offline, Emergency SOS"
publish_to: 'none'

version: 3.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Networking
  http: ^1.2.1
  connectivity_plus: ^6.1.3

  # Auth & Storage
  shared_preferences: ^2.2.3

  # Voice & Translation
  speech_to_text: ^6.6.2
  flutter_tts: ^4.2.2
  audioplayers: ^6.1.0
  google_mlkit_translation: ^0.13.0

  # State Management
  provider: ^6.1.2

  # UI & Fonts
  google_fonts: ^6.2.1
  animate_do: ^3.3.4
  shimmer: ^3.0.0

  # Advanced Features
  intl: ^0.19.0
  path_provider: ^2.1.3
  flutter_local_notifications: ^17.2.4
  image_picker: ^1.1.2

  # Live Map
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2

  # UI extras
  percent_indicator: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/emergency/
    - assets/home.jpg
    - assets/profile.jpg
    - assets/sos.jpg
    - assets/icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
